

export default [
  {
    name: 'Zhowtime',
    description:'Have you ever wondered how many goals Zlatan Ibrahimovic has scored in the Champions League?  Well, you can finally see every single goal he ever made on Zhowtime.com.',
    long_desc:"I worked with a designer and had all responsibility for the development of the site by my self. The Site is down now because we missed the rights to some of the videos.",
    duration: '2015-2016',
    slug: 'zhowtime',
    img:['z1.jpg','2.jpg'],
    order: 0,
    properties: { className: 'black' },
    role: 'Front-end/ Backend / Devop/ UX',
    stack: 'HTML, CSS, Javascript, PHP',
    website: '',

  },
    {
    name: 'ToolPool',
    description:"ToolPool is like a carpool, but with tools and it's free",
    long_desc:"Malmö Hardware Store needed an idea to be able to compete with the giant home improvement chains that are taking over the market. We learned that the stores main earnings comes from supplies, not from expensive tools. So we created ToolPool. It works just like a carpool, but with tools. And its for free. All we ask for in return is that you share our message on Facebook.<br> During the very first month, ToolPool received extensive media coverage, over 600 members and sales in the store increased by 25%.<br><br>  ToolPool has been awarded in Cannes Lions (Silver Lion in Promo & Activation, Bronze Lion in Cyber and Shortlist in Media), GuldÃ¤gget (Golden Egg in PR, Silver Egg in Digital and Silver Egg in Alternative Media), Tomorrow Awards (Shortlist), Spinn (Shortlist x3), Best Ads (Gold), Campaign of the Month, Interactive (Gold), 100-wattaren (Gold) and published in Contagius Magazine.",
    duration: '2012-2015',
    slug: 'toolpool',
    img:['t1.jpg'],
    order: 0,
    properties: { className: 'toolpool' },
    role: 'Front-end/ Backend',
    stack: 'HTML, CSS, Javascript, PHP',
    website: 'https://www.facebook.com/toolpoolmalmo/',

  },
    {
    name: 'Wilfa Svart',
    description:'NORDISK PASSION',
    long_desc:"The mission was to produce a product page where we will tell you more about the Wilfa Black series, with new environmental images and Nordic feel. Work with a digital designer and copywriterto make this platform.",
    duration: '2017',
    slug: 'wilfa-svart',
    img:['w1.jpg'],
    order: 0,
    properties: { className: 'gray' },
    role: 'Front-end / Backend / Devop / UX',
    stack: 'HTML, CSS, Javascript, Wordpress, LNMP7',
    website: 'http://www.wilfasvart.se',
  },
  {
    name: 'Malmö Saluhall',
    description:'With a new brand identity, Malmö Saluhall needed to update the digital profile of the website.',
    long_desc:"I worked with a art director and digital designer to built the website.",
    duration: '2017',
    slug: 'malmo-saluhall',
    img:['ms.jpg'],
    order: 0,
    properties: { className: 'brun' },
    role: 'Front-end / Backend / Devop',
    stack: 'HTML, CSS, Javascript, Wordpress',
    website: 'http://www.malmosaluhall.se',
  },
  {
    name: 'Mekonomen',
    description:'The mission was to build a web platform that Mekonomen could use on several of its sites.',
    long_desc:"We received a Graphic Profile and a styleguide in Sketch format by Mekonomen. Worked together in an agile team where I was responsible for the entire project together with a front end/UX and a Backend developer. After we went live, I took care of the maintenance of the site, Bug fix and also the Mekonomen servers (Stage & Prod) / RHEL.",
    duration: '2015-2016',
    slug: 'mekonomen',
    img:['mek.jpg'],
    order: 0,
    properties: { className: 'yellow' },
    role: 'Front-end / Backend',
    stack: 'PHP, Wordpress, HTML, CSS, Javascript, Google Maps Api, SOAP',
    website: 'http://www.mekonomen.dk/',
  },
  {
    name: 'Mekonomen Group.',
    description:'We built a new site for the Mekonomen Group.',
    long_desc:"I worked with a front-end developer who delivered a style guide with html code that I got sewn together into a website.",
    duration: '2016',
    slug: 'mekonomen-group',
    img:['mekg.jpg'],
    order: 0,
    properties: { className: 'mekonomen' },
    role: 'Front-end / Backend / Devop',
    stack: 'PHP, Wordpress, HTML, CSS, Javascript, SOAP',
    website: 'http://www.mekonomen.com',
  },
  {
    name: 'Symsoft',
    description:"Cloud Communications for the World's Most Demanding Enterprises",
    long_desc:"I got into the team in the middle of the project and got work mostly with bug fixes & backend but also adding new features and front-end for new parts of the site. I also took care of their servers (stage, prod) Ubuntu.",
    duration: '2015-2016',
    slug: 'clx-symsoft',
    img:['sym.jpg'],
    order: 0,
    properties: { className: 'symsoft' },
    role: 'Front-end / Backend / Devop',
    stack: 'Wordpress, HTML, CSS, Javascript',
    website: 'https://www.symsoft.com',
  },
  {
    name: 'Äppleappen',
    description:'A pomologist on the phone - Discover Swedish apples in your phone',
    long_desc:"I worked together in a team of a designer and two full stack developers , we built Android and the web version of the app iPhone app.",
    duration: '2015',
    slug: 'appleapp',
    img:['apple.jpg',],
    order: 0,
    properties: { className: 'appleapp' },
    role: 'Front-end / Mobile',
    stack: 'Phonegap, Angular, HTML, CSS',
    website: 'https://www.nordiskamuseet.se/svenskaapplen',
  },
  {
    name: 'Soctanter',
    description:'Soctanter på nätet',
    long_desc:"The mission was to move the old Soctanter site to a new platform (Drupal forum). But in the pre studies of the project, we had the chanse to meet with moderators who worked with the website and felt how difficult it would be for them to use a forum. After some meeting with those responsible for the Soctanter, we were assigned to developing a new platform that users could use to submit questions and moderators got to answer them. Also, the backend was built so that Soctanter who were to work could have all the features they needed.",
    duration: '2015',
    slug: 'soctanter',
    img:['soc.jpg'],
    order: 0,
    properties: { className: 'soctanter' },
    role: 'Front-end / Backend',
    stack: 'PHP, Drupal, HTML, CSS',
    website: 'https://soctanter.malmo.se/',
  },
    {
    name: 'Kammarkollegiet',
    description:'Building a new website for government organization.',
    long_desc:"The mission was to move the old Soctanter site to a new platform (Drupal forum). But in the pre studies of the project, we had the chanse to meet with moderators who worked with the website and felt how difficult it would be for them to use a forum. After some meeting with those responsible for the Soctanter, we were assigned to developing a new platform that users could use to submit questions and moderators got to answer them. Also, the backend was built so that Soctanter who were to work could have all the features they needed.",
    duration: '2015',
    slug: 'kammarkollegiet',
    img:['kam.jpg'],
    order: 0,
    properties: { className: 'kammarkollegiet' },
    role: 'Front-end / Backend',
    stack: 'PHP, Drupal, HTML, CSS, Javascript, Accessibility',
    website: 'https://www.kammarkollegiet.se',
  },
      {
    name: 'Muslimix',
    description:'FINAX well known FCMG brand and famous muesli maker wanted to engage with consumers by combining music and the muesli ingredients through an interactive and social media based web-campaign. The criteria were; a fun, easy-to-use and cool sounding application.',
    long_desc:"So The Fan Club and Magisty developed a web campaign application that enabled the user to mix ingredients into customized bags of muesli, just like a DJ mixing different beats and sound effects into cool dance tunes. Consumers mixed their own blends and the beats were shared in their fb-feeds for competing to win a yearâ€™s supply of FINAX breakfast cereals.<br><br>The result; a successful campaign and a web based application using the latest HTML5 sound technology including a social media campaign with voting, rating and sharing functionality. Also, a lot of cool beats.",
    duration: '2014',
    slug: 'muslimix',
    img:['mm.jpg'],
    order: 0,
    properties: { className: 'muslimix' },
    role: 'UX / Design',
    stack: 'Photoshop',
    website: '',
  }

  ];